language: java
notifications:
  slack: mishima-group:8zsPeLEBTdLyT7kCZdQzIx4c
deploy:
  provider: heroku
  app: callrecorder
  api_key:
    secure: BXxXNwSGuw7a3GifIJYFA5KuFDtZAi4d28p/nQda4ZWR2aSFW+jmvPBi7Az0YL0YSmhHjH6o4szx4yCHtmh0zAmHzTfs2p/KcuhH9EDFnNS7//tBkVXhyUvUhzygTNKK6FjX123pi9NE48cnnr3mRfAqZ8ma8YoGm+SPRDfXNq2z/HVdmBFEAhoGdC7vOjL/e+IJ5t9B9JllUdGOaJE62YIBB6YXQbAJgIRwzZyVeOKjObbT9v2v3ykDESm+0xycHXBUPhcumtp3VFWk5n1PPKoKVYd+Un2hGRjQUTw8HGERop8MF/m0bKPZGENPGXNUSFpN+OQF/dz+RzKOjRRT+zF5HBbVFbDz3erI/bMK+KCwrtTA4BBv/N/XfGLl08Rh7Uo2xseVX7mUFWHMkMeNbhGSFLnYD/4b7/dO+jMYavlfRf0j0cicv0Iqp48XTeQCR87uQ6vVC0QADsRtXjH8FYa1KOK9xYB68fjvZ4sIE5KEzF9nTgoelTu1g3GJMIbPqkq9hzn3AZogpfltjnInhMDOO/dcbC4PZ4d+v5H0oPxoqCQw6LRegBpbVnrQEQbpRSU8Dv5ySyIAdGCBKYk4whp6PAbBjRH3aYvHJ/QzfX7wuAAqIuNxUkcCx9MO4PtS+VCmN19CA21bS6R2iDTtdVgQbW8xK8LumwemTQQattU=
